version:  '3.8'

services:

  app:
    environment:
      SECRET_KEY: fwyAOBGEXy2mCOqjHh6j
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin:5.2.1
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - flask-app
